export const WINDOW_PROJECTS_LOADED_ARCHIVED_EPOCHS_NUMBER =
  'WINDOW_PROJECTS_LOADED_ARCHIVED_EPOCHS_NUMBER';
export const WINDOW_PROJECTS_SCROLL_Y = 'WINDOW_PROJECTS_SCROLL_Y';
export const CYPRESS_IS_PROJECT_ADMIN = 'CYPRESS_IS_PROJECT_ADMIN';
