export const QUERY_KEYS = {
  currentBalance: ['currentBalance'],
  currentEpoch: ['currentEpoch'],
  decisionWindow: ['decisionWindow'],
  depositAt: ['depositAt'],
  depositAtGivenEpoch: (epochNumber: number): string[] => [
    ...QUERY_KEYS.depositAt,
    epochNumber.toString(),
  ],
  depositsValue: ['depositsValue'],
  epochDuration: ['epochDuration'],
  epochProps: (index: number): string[] => ['epochProps', index.toString()],
  epochPropsIndex: ['epochPropsIndex'],
  glmLocked: ['glmLocked'],
  individualReward: ['individualReward'],
  isDecisionWindowOpen: ['isDecisionWindowOpen'],
  lockedRatio: ['lockedRatio'],
  matchedProposalRewards: ['matchedProposalRewards'],
  matchedRewards: ['matchedRewards'],
  proposalRewardsThresholdFraction: ['proposalRewardsThresholdFraction'],
  proposalsCid: ['proposalsCid'],
  proposalsContract: ['proposalsContract'],
  proposalsIpfsResults: (address: string): string[] => ['proposalsIpfsResults', address],
  start: ['start'],
  userAllocations: ['userAllocations'],
  usersWithTheirAllocations: (proposalAddress: string): string[] => [
    'usersWithTheirAllocations',
    proposalAddress,
  ],
};
