/* eslint-disable */
// @ts-nocheck
// This file was autogenerated by ethereum-abi-types-generator
import BN from 'bn.js';
import BigNumber from 'bignumber.js';
import {
  PromiEvent,
  TransactionReceipt,
  EventResponse,
  EventData,
  Web3ContractContext,
} from 'ethereum-abi-types-generator';

export interface CallOptions {
  from?: string;
  gasPrice?: string;
  gas?: number;
}

export interface SendOptions {
  from: string;
  value?: number | string | BN | BigNumber;
  gasPrice?: string;
  gas?: number;
}

export interface EstimateGasOptions {
  from?: string;
  value?: number | string | BN | BigNumber;
  gas?: number;
}

export interface MethodPayableReturnContext {
  send(options: SendOptions): PromiEvent<TransactionReceipt>;
  send(
    options: SendOptions,
    callback: (error: Error, result: any) => void,
  ): PromiEvent<TransactionReceipt>;
  estimateGas(options: EstimateGasOptions): Promise<number>;
  estimateGas(
    options: EstimateGasOptions,
    callback: (error: Error, result: any) => void,
  ): Promise<number>;
  encodeABI(): string;
}

export interface MethodConstantReturnContext<TCallReturn> {
  call(): Promise<TCallReturn>;
  call(options: CallOptions): Promise<TCallReturn>;
  call(
    options: CallOptions,
    callback: (error: Error, result: TCallReturn) => void,
  ): Promise<TCallReturn>;
  encodeABI(): string;
}

export interface MethodReturnContext extends MethodPayableReturnContext {}

export type ContractContext = Web3ContractContext<
  Proposals,
  ProposalsMethodNames,
  ProposalsEventsContext,
  ProposalsEvents
>;
export type ProposalsEvents = 'EpochsSet';
export interface ProposalsEventsContext {
  EpochsSet(
    parameters: {
      filter?: {};
      fromBlock?: number;
      toBlock?: 'latest' | number;
      topics?: string[];
    },
    callback?: (error: Error, event: EventData) => void,
  ): EventResponse;
}
export type ProposalsMethodNames =
  | 'new'
  | 'auth'
  | 'cid'
  | 'epochs'
  | 'getProposalAddresses'
  | 'setCID'
  | 'setEpochs'
  | 'setProposalAddresses';
export interface EpochsSetEventEmittedResponse {
  epochs: string;
}
export interface Proposals {
  /**
   * Payable: false
   * Constant: false
   * StateMutability: nonpayable
   * Type: constructor
   * @param _initCID Type: string, Indexed: false
   * @param proposals Type: address[], Indexed: false
   * @param _auth Type: address, Indexed: false
   */
  'new'(_initCID: string, proposals: string[], _auth: string): MethodReturnContext;
  /**
   * Payable: false
   * Constant: true
   * StateMutability: view
   * Type: function
   */
  auth(): MethodConstantReturnContext<string>;
  /**
   * Payable: false
   * Constant: true
   * StateMutability: view
   * Type: function
   */
  cid(): MethodConstantReturnContext<string>;
  /**
   * Payable: false
   * Constant: true
   * StateMutability: view
   * Type: function
   */
  epochs(): MethodConstantReturnContext<string>;
  /**
   * Payable: false
   * Constant: true
   * StateMutability: view
   * Type: function
   * @param _epoch Type: uint256, Indexed: false
   */
  getProposalAddresses(_epoch: string): MethodConstantReturnContext<string[]>;
  /**
   * Payable: false
   * Constant: false
   * StateMutability: nonpayable
   * Type: function
   * @param _newCID Type: string, Indexed: false
   */
  setCID(_newCID: string): MethodReturnContext;
  /**
   * Payable: false
   * Constant: false
   * StateMutability: nonpayable
   * Type: function
   * @param _epochs Type: address, Indexed: false
   */
  setEpochs(_epochs: string): MethodReturnContext;
  /**
   * Payable: false
   * Constant: false
   * StateMutability: nonpayable
   * Type: function
   * @param _epoch Type: uint256, Indexed: false
   * @param _proposalAddresses Type: address[], Indexed: false
   */
  setProposalAddresses(_epoch: string, _proposalAddresses: string[]): MethodReturnContext;
}
