# contains services shared by localenv and apitest environments

version: "3.8"
services:

  graph-node:
    image: graphprotocol/graph-node:v0.35.1
    platform: linux/amd64
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    networks:
      - octant
    depends_on:
      - ipfs
      - graph-postgres
    environment:
      NETWORK_NAME: localhost
      RPC_PROVIDER: http://anvil:8545
      postgres_host: graph-postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: localhost:http://anvil:8545
      GRAPH_LOG: debug
      ETHEREUM_REORG_THRESHOLD: 0

  ipfs:
    image: ipfs/kubo:v0.27.0
    ports:
      - '5001:5001'
    networks:
      - octant

  graph-postgres:
    image: postgres
    ports:
      - '5433:5432'
    networks:
      - octant
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'

  multideployer:
    image: octant/multideployer:latest
    networks:
      - octant
    depends_on:
      - anvil
      - graph-node
    ports:
      - '8022:8022'
    environment:
      RPC_URL: http://anvil:8545
      NETWORK: localhost
      SKIP_LOCAL_SUBGRAPH_UPDATE: true
      EPOCH_DURATION: 600

      PROPOSALS_CID: QmXq3Eaz5xQF51J7mWzxDmfrVjDuGdhnirthttJ9Q2WTF8
      PROPOSALS_ADDRESSES: 0x13aB14d9f8a40a0a19f7c8Ba8B23a3F12D25fD12,0x50b641Fb1CC42bE8a292263c68f0612b8182dA51,0x519a0307b7364D21aB1227bf37689271233B3F93,0x5a873cB89BAd323b1acfd998C36aAc6b1a90a91d,0x608309bF063599DdaaF79409879917032377AC44,0x6d614D51D1Ed4eE97A37614F431771Fdb92D5Ae7,0x839a14166Af647F9DD5CdeA616c0354286Cc1593,0xBfD2704FEbD0d6A3f82Ed338731Fdf63077F76Fa,0xdE49c0928ECC3cfb5d07F69f5C82949168Fc6805,0xeAe7825257E71ba345FFcC54D0581ccE819738B9

      IPFS_URL: http://ipfs:5001
      SUBGRAPH_ADMIN_URL: http://graph-node:8020
      SUBGRAPH_QUERY_URL: http://graph-node:8000

networks:
  octant:
