# services used by localenv; use with docker-compose.yaml

version: "3.8"
services:


  anvil:
    image: octant/anvil:latest
    platform: linux/amd64
    command: '--block-time "${BLOCK_TIME:-5}"'
    ports:
      - "8545:8545"
    networks:
      - octant


  backend-postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: octant
    networks:
      - octant


  backend:
    image: octant/backend:latest
    platform: linux/amd64
    ports:
      - '5010:5000'
    environment:
      CONTRACTS_DEPLOYER_URL: 'http://multideployer:8022/?name=octant'

      OCTANT_ENV: production
      DB_URI: "postgresql://user:password@backend-postgres:5432/octant"
      SUBGRAPH_ENDPOINT: "http://graph-node:8000/subgraphs/name/octant"

      ETH_RPC_PROVIDER_URL: "http://anvil:8545"
      CHAIN_ID: "1337"
      CHAIN_NAME: "localhost"

      GC_PASSPORT_SCORER_API_KEY: "${GC_PASSPORT_SCORER_API_KEY}"
      GC_PASSPORT_SCORER_ID: "${GC_PASSPORT_SCORER_ID}"

      DELEGATION_SALT: "salt"
      DELEGATION_SALT_PRIMARY: "salt_primary"

    depends_on:
      - backend-postgres
      - anvil
      - graph-node
      - multideployer
    networks:
      - octant


  epochs-snapshotter:
    image: 'octant/snapshotter:latest'
    depends_on:
      - backend
    networks:
      - octant


  control-plane:
    image: octant/control-plane:latest
    ports:
      - "8080:80"
    networks:
      - octant
    depends_on:
      - backend
      - anvil
      - graph-node
      - multideployer


networks:
  octant:
