FROM node:16-alpine AS root
WORKDIR /app

FROM root AS build
#RUN apk add git
COPY package.json yarn.lock ./
RUN yarn install --ignore-scripts --frozen-lockfile
COPY ./ ./
RUN yarn compile
RUN rm -Rf cache/

FROM root AS deploy
# When dependencies will be used instead of using only devDependencies
#COPY ./ ./
# RUN yarn install --prod --ignore-scripts --frozen-lockfile && yarn cache clean
COPY --from=build /app/ /app/
ENTRYPOINT [ "/app/entrypoint.sh" ]
CMD [ "goerli" ]
