FROM local-docker-registry.wildland.dev/library/node:16-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --ignore-scripts --frozen-lockfile && yarn cache clean
COPY ./ ./

ENTRYPOINT ["yarn", "run", "build"]
