FROM local-docker-registry.wildland.dev:80/library/node:18-alpine AS root

WORKDIR /app

FROM root AS build
RUN apk add git
COPY ./ ./
RUN yarn install --ignore-scripts --frozen-lockfile

FROM root AS deploy
RUN apk add jq gettext-envsubst
ARG VERSION_TAG
ENV VERSION_TAG=$VERSION_TAG
COPY --from=build /app/ /app/
ENTRYPOINT [ "/app/entrypoint.sh" ]
