FROM local-docker-registry.wildland.dev:80/library/node:20-alpine

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --ignore-scripts --frozen-lockfile && yarn cache clean
COPY ./ ./

ENTRYPOINT ["yarn", "run", "build"]
