FROM local-docker-registry.wildland.dev:80/library/node:20-alpine AS root

WORKDIR /app
COPY package.json yarn.lock ./

FROM root AS build
RUN yarn install --ignore-scripts --frozen-lockfile
COPY tsconfig.json ./
COPY src/* src/
RUN yarn build

FROM root AS deploy
EXPOSE 3000
CMD [ "node", "index.js" ]

RUN yarn install --prod --ignore-scripts --frozen-lockfile && yarn cache clean
COPY --from=build /app/dist/* ./
