"""empty message

Revision ID: 0e5f1447625e
Revises: e1f51b19e6f0
Create Date: 2023-06-19 16:07:42.969909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e5f1447625e"
down_revision = "e1f51b19e6f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked_ratio", sa.String(), nullable=False))
        batch_op.drop_column("staked_ratio")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("staked_ratio", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("locked_ratio")

    # ### end Alembic commands ###
