"""empty message

Revision ID: 16ed3f1d5233
Revises: bd79c598c867
Create Date: 2023-07-31 13:25:54.696247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16ed3f1d5233"
down_revision = "bd79c598c867"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_consents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_consents")
    # ### end Alembic commands ###
