"""empty message

Revision ID: 1d3a470b8cf8
Revises: 234c46eecc33
Create Date: 2023-05-09 15:51:43.230369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3a470b8cf8'
down_revision = '234c46eecc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
