"""empty message

Revision ID: 35833fb452c1
Revises: 0e5f1447625e
Create Date: 2023-06-22 11:13:51.221177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35833fb452c1"
down_revision = "0e5f1447625e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finalized_epoch_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("withdrawals_merkle_root", sa.String(), nullable=False),
        sa.Column("total_withdrawals", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epoch"),
    )
    op.create_table(
        "pending_epoch_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("glm_supply", sa.String(), nullable=False),
        sa.Column("eth_proceeds", sa.String(), nullable=False),
        sa.Column("total_effective_deposit", sa.String(), nullable=False),
        sa.Column("locked_ratio", sa.String(), nullable=False),
        sa.Column("total_rewards", sa.String(), nullable=False),
        sa.Column("vanilla_individual_rewards", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epoch"),
    )
    op.create_table(
        "rewards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("amount", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("epoch_snapshots")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epoch_snapshots",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("epoch", sa.INTEGER(), nullable=False),
        sa.Column("glm_supply", sa.VARCHAR(), nullable=False),
        sa.Column("eth_proceeds", sa.VARCHAR(), nullable=False),
        sa.Column("total_effective_deposit", sa.VARCHAR(), nullable=False),
        sa.Column("total_rewards", sa.VARCHAR(), nullable=False),
        sa.Column("vanilla_individual_rewards", sa.VARCHAR(), nullable=False),
        sa.Column("locked_ratio", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epoch"),
    )
    op.drop_table("rewards")
    op.drop_table("pending_epoch_snapshots")
    op.drop_table("finalized_epoch_snapshots")
    # ### end Alembic commands ###
