"""empty message

Revision ID: 41176b6c1960
Revises: aadacb624887
Create Date: 2023-10-04 16:57:34.285138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41176b6c1960"
down_revision = "aadacb624887"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patrons_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("toggle", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("patrons_events")
    # ### end Alembic commands ###
