"""empty message

Revision ID: 5d3b741a454d
Revises: 1d3a470b8cf8
Create Date: 2023-05-10 10:53:23.470233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d3b741a454d"
down_revision = "1d3a470b8cf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onchain_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch_no", sa.Integer(), nullable=False),
        sa.Column("glm_supply", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epoch_no"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("onchain_snapshot")
    # ### end Alembic commands ###
