"""empty message

Revision ID: 7509cfc0824d
Revises: 35833fb452c1
Create Date: 2023-06-27 15:45:08.661862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7509cfc0824d"
down_revision = "35833fb452c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table("finalized_epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column(
            "withdrawals_merkle_root", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "total_withdrawals", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table("rewards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("rewards", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("finalized_epoch_snapshots", schema=None) as batch_op:
        batch_op.alter_column(
            "total_withdrawals", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "withdrawals_merkle_root", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("created_at")

    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
