"""add user budgets table

Revision ID: 794617984fc3
Revises: 449308032075
Create Date: 2024-01-02 12:03:50.556160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "794617984fc3"
down_revision = "449308032075"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("budget", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budgets")
    # ### end Alembic commands ###
