"""empty message

Revision ID: 8947024866a8
Revises: 4371054aa069
Create Date: 2023-12-04 13:06:21.587712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8947024866a8"
down_revision = "4371054aa069"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("budget", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budgets")
    # ### end Alembic commands ###
