"""empty message

Revision ID: aadacb624887
Revises: 79532eaf12d0
Create Date: 2023-10-03 15:58:48.710448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aadacb624887"
down_revision = "79532eaf12d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.drop_column("glm_supply")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("glm_supply", sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
