"""empty message

Revision ID: bd79c598c867
Revises: f9b48943e363
Create Date: 2023-07-11 13:57:06.271299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd79c598c867"
down_revision = "f9b48943e363"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epoch_zero_claims",
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("claimed", sa.Boolean(), nullable=True),
        sa.Column("claim_nonce", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
        sa.UniqueConstraint("claim_nonce"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            "glm_withdrawal_nonce_unique_constraint", type_="unique"
        )
        batch_op.drop_column("glm_withdrawn")
        batch_op.drop_column("glm_withdrawal_nonce")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("glm_withdrawal_nonce", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("glm_withdrawn", sa.BOOLEAN(), nullable=True))
        batch_op.create_unique_constraint(
            "glm_withdrawal_nonce_unique_constraint", ["glm_withdrawal_nonce"]
        )

    op.drop_table("epoch_zero_claims")
    # ### end Alembic commands ###
