"""add patrons_rewards, leftover and operational_cost to snapshots

Revision ID: d381462203ad
Revises: 449308032075
Create Date: 2024-01-02 16:17:53.740348

"""
import os

from alembic import op
import sqlalchemy as sa
from dotenv import load_dotenv

# revision identifiers, used by Alembic.
revision = "d381462203ad"
down_revision = "449308032075"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finalized_epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "patrons_rewards", sa.String(), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(
            sa.Column("leftover", sa.String(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "operational_cost", sa.String(), nullable=False, server_default="0"
            )
        )
    # ### end Alembic commands ###

    if op.get_bind().engine.name == "sqlite":
        return

    load_dotenv()
    # Mainnet
    if os.getenv("CHAIN_ID") == "1":
        _execute_mainnet_sql()
    # Sepolia
    if os.getenv("CHAIN_ID") == "11155111":
        _execute_sepolia_sql()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_epoch_snapshots", schema=None) as batch_op:
        batch_op.drop_column("operational_cost")

    with op.batch_alter_table("finalized_epoch_snapshots", schema=None) as batch_op:
        batch_op.drop_column("leftover")
        batch_op.drop_column("patrons_rewards")

    # ### end Alembic commands ###


def _execute_mainnet_sql():
    # Update pending snapshots
    op.execute(
        "UPDATE pending_epoch_snapshots SET operational_cost = '82408409816289053184' WHERE epoch = 1"
    )
    op.execute(
        "UPDATE pending_epoch_snapshots SET operational_cost = '241664279869852205390' WHERE epoch = 2"
    )

    # Update finalized snapshots
    op.execute(
        "UPDATE finalized_epoch_snapshots SET leftover = '9537357664505573437' WHERE epoch = 1"
    )
    op.execute(
        "UPDATE finalized_epoch_snapshots SET patrons_rewards = '16050223937523865304' WHERE epoch = 1"
    )
    op.execute(
        "UPDATE finalized_epoch_snapshots SET leftover = '359759748331066181593' WHERE epoch = 2"
    )
    op.execute(
        "UPDATE finalized_epoch_snapshots SET patrons_rewards = '8695859401745522' WHERE epoch = 2"
    )


def _execute_sepolia_sql():
    op.execute(
        "UPDATE pending_epoch_snapshots SET operational_cost = '22286773660600424828954' WHERE epoch = 1"
    )
    op.execute(
        "UPDATE pending_epoch_snapshots SET operational_cost = '28130172997690715704718' WHERE epoch = 2"
    )

    # Update finalized snapshots
    op.execute(
        "UPDATE finalized_epoch_snapshots SET leftover = '2859407787364580036791' WHERE epoch = 1"
    )
    op.execute(
        "UPDATE finalized_epoch_snapshots SET leftover = '3574815154956933931971' WHERE epoch = 2"
    )
