"""empty message

Revision ID: e1f51b19e6f0
Revises: a78f214addc4
Create Date: 2023-05-31 11:59:15.854561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1f51b19e6f0"
down_revision = "a78f214addc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("epoch_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("staked_ratio", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("total_rewards", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("vanilla_individual_rewards", sa.String(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("epoch_snapshots", schema=None) as batch_op:
        batch_op.drop_column("vanilla_individual_rewards")
        batch_op.drop_column("total_rewards")
        batch_op.drop_column("staked_ratio")

    # ### end Alembic commands ###
