"""add patron mode toggles table

Revision ID: f81d796a7ab8
Revises: 4371054aa069
Create Date: 2023-12-04 01:55:29.065104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f81d796a7ab8"
down_revision = "4371054aa069"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patron_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_address", sa.String(length=42), nullable=False),
        sa.Column("patron_mode_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("patron_mode")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("patron_mode", sa.BOOLEAN(), nullable=False))

    op.drop_table("patron_events")
    # ### end Alembic commands ###
