"""empty message

Revision ID: f9b48943e363
Revises: a49d3e62bda9
Create Date: 2023-07-04 10:15:37.497160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9b48943e363"
down_revision = "a49d3e62bda9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("allocation_nonce", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("glm_withdrawn", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("glm_withdrawal_nonce", sa.Integer(), nullable=True)
        )
        batch_op.create_unique_constraint(
            "glm_withdrawal_nonce_unique_constraint", ["glm_withdrawal_nonce"]
        )
        batch_op.drop_column("nonce")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nonce", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("glm_withdrawal_nonce")
        batch_op.drop_column("glm_withdrawn")
        batch_op.drop_column("allocation_nonce")

    # ### end Alembic commands ###
