"""add_timestamps_to_allocations

Revision ID: fa5dac1a1dc4
Revises: 0e5f1447625e
Create Date: 2023-06-23 15:27:29.341221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa5dac1a1dc4"
down_revision = "0e5f1447625e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
