#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd client
yarn install

cd ../contracts
yarn install
yarn compile

cd ../contracts-v1
yarn install
yarn compile

cd ../coin-prices-server
yarn install

cd ../subgraph
yarn install
yarn codegen

cd ../backend
poetry install
poetry run flake8
poetry run black --check .

cd ..
yarn lint-staged
