#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd client
yarn install
yarn type-check

cd ../contracts
yarn install
yarn clean
yarn compile
yarn type-check

cd ../contracts-v1
yarn install
yarn clean
yarn compile
yarn type-check

cd ../coin-prices-server
yarn install
yarn type-check

cd ../backend
poetry install
poetry run flake8
poetry run black --check .
