---
name: ▶️ Deploy Master
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/tpl-images.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
  run:
    name: Run
    uses: ./.github/workflows/tpl-start-env.yml
    secrets: inherit
    with:
      git-ref: ${{ github.ref }}
      env-type: master
      workflow-id: ${{ github.run_id }}
  deploy:
    name: Deploy
    needs:
    - build
    - run
    uses: ./.github/workflows/tpl-deploy-app.yml
    with:
      env-type: master
      branch-head-ref: ${{ github.ref }}
      env-id: ${{ needs.run.outputs.env-id }}
      deployment-id: ${{ needs.run.outputs.deployment-id }}
      image-tag: ${{ github.sha }}
      workflow-id: ${{ github.run_id }}
      # ---
      chain-id: 11155111
      network-name: sepolia
      chain-name: sepolia
      snapshotter-enabled: true
      scheduler-enabled: true
      vault-confirm-withdrawals-enabled: true
      glm-claim-enabled: true
    secrets: inherit
