---
name: ▶️ Deploy UAT
on:
  workflow_dispatch:
    inputs:
      redeploy_contracts:
        description: 'redeploy contracts'
        required: true
        type: boolean

jobs:
  build:
    name: Build
    uses: ./.github/workflows/tpl-images.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
  run:
    name: Run
    uses: ./.github/workflows/tpl-start-env.yml
    secrets: inherit
    with:
      git-ref: ${{ github.ref }}
      env-type: uat
      workflow-id: ${{ github.run_id }}
  deploy:
    name: Deploy
    needs:
    - build
    - run
    uses: ./.github/workflows/tpl-deploy-app.yml
    with:
      env-type: uat
      branch-head-ref: ${{ github.ref }}
      env-id: ${{ needs.run.outputs.env-id }}
      deployment-id: ${{ needs.run.outputs.deployment-id }}
      image-tag: ${{ github.sha }}
      workflow-id: ${{ github.run_id }}
      # ---
      deploy-contracts: ${{ inputs.redeploy_contracts }}
      chain-id: 11155111
      network-name: sepolia
      chain-name: sepolia
      snapshotter-enabled: true
      scheduler-enabled: true
      vault-confirm-withdrawals-enabled: true
      glm-claim-enabled: true
      decision-window: 1800
      epoch-duration: 3600
    secrets: inherit
