---
name: 🔻 Stop Master
on:
  workflow_dispatch:

jobs:
  run:
    name: Run
    uses: ./.github/workflows/tpl-destroy-env.yml
    secrets: inherit
    with:
      env-type: master
      delete-env: false
