---
name: 🔒 Docker Images
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      git-ref:
        required: true
        type: string
concurrency:
  group: "${{ github.ref }}-images"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-images:
    name: Build Docker Image
    runs-on:
      - general
    strategy:
      matrix:
        SERVICE:
        - contracts-v1
        - coin-prices-server
        - client
        - subgraph
        - backend
    steps:
    - uses: actions/checkout@v4
      with:
        # use some obscure path to checkout the code with service account perms
        # this is possible as $GITHUB_WORKSPACE is owned by the same service
        # account
        # see: https://github.com/actions/checkout/issues/211
        path: __local
        ref: ${{ inputs.git-ref }}

    - name: Set DOCKER_CONFIG
      run: |
        echo "DOCKER_CONFIG=${RUNNER_TEMP}/docker-config-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-${{ matrix.SERVICE }}" >> "$GITHUB_ENV"
      shell: bash

    - name: Authenticate to GCP (WIF)
      id: gcp-auth
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
        service_account: ${{ vars.GCP_WIF_SA_DEV_WRITER }}
        token_format: access_token

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      with:
        cosign-release: 'v2.6.3'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
        driver-opts: network=host
        driver: docker-container
        buildkitd-config-inline: |
          debug = true
          insecure-entitlements = [ "network.host" ]

          [registry."local-docker-registry.wildland.dev:80"]
          http = true

    - name: set variables
      env:
        NORMALIZED_NAME: ${{ matrix.SERVICE }}
      run: |
        NORMALIZED_NAME=${{ env.NORMALIZED_NAME }}
        NORMALIZED_NAME=${NORMALIZED_NAME//\//-} # replace / with -
        echo NORMALIZED_NAME=${NORMALIZED_NAME} >> $GITHUB_ENV # update GitHub ENV vars
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        allow: network.host
        context: __local/${{ matrix.SERVICE }}
        file: __local/ci/Dockerfile.${{ env.NORMALIZED_NAME }}
        push: true
        tags: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/${{ env.NORMALIZED_NAME }}:${{ inputs.image-tag }}
        # cache-from: type=local,src=/mnt/storage/kaniko-cache
        # cache-to: type=local,dest=/mnt/storage/kaniko-cache

    - name: Sign the image with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build.outputs.digest }}
        TAG: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/${{ env.NORMALIZED_NAME }}:${{ inputs.image-tag }}
      run: cosign sign --yes "${TAG}@${DIGEST}"
      shell: bash

  build-multideployer:
    name: Build Multideployer (special case)
    needs:
      - build-images
    runs-on:
      - general
    steps:
    - uses: actions/checkout@v4
      with:
        path: __local
        ref: ${{ inputs.git-ref }}

    - name: Set DOCKER_CONFIG
      run: |
        echo "DOCKER_CONFIG=${RUNNER_TEMP}/docker-config-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-${GITHUB_JOB}" >> "$GITHUB_ENV"
      shell: bash

    - name: Authenticate to GCP (WIF)
      id: gcp-auth
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
        service_account: ${{ vars.GCP_WIF_SA_DEV_WRITER }}
        token_format: access_token

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      with:
        cosign-release: 'v2.6.3'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
        driver: docker-container
        driver-opts: network=host
        buildkitd-config-inline: |
          debug = true
          insecure-entitlements = [ "network.host" ]
          [registry."local-docker-registry.wildland.dev:80"]
            http = true

    - name: replace placeholders
      run: |
        sed -i 's|_CONTRACTS_IMAGE_PLACEHOLDER_|${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/contracts-v1:${{ inputs.image-tag }}|g' __local/ci/Dockerfile.multideployer
        sed -i 's|_SUBGRAPH_IMAGE_PLACEHOLDER_|${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/subgraph:${{ inputs.image-tag }}|g' __local/ci/Dockerfile.multideployer
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        allow: network.host
        context: __local/localenv/multideployer
        file: __local/ci/Dockerfile.multideployer
        push: true
        tags: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/multideployer:${{ inputs.image-tag }}

    - name: Sign the image with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build.outputs.digest }}
        TAG: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/multideployer:${{ inputs.image-tag }}
      run: cosign sign --yes "${TAG}@${DIGEST}"
      shell: bash
