---
name: 🔒 Docker Images
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      git-ref:
        required: true
        type: string
concurrency:
  group: "${{ github.ref }}-images"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-images:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: actions
    strategy:
      matrix:
        SERVICE:
        - contracts-v1
        - coin-prices-server
        - client
        - subgraph
        - backend
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.git-ref }}

    - name: set variables
      env:
        NORMALIZED_NAME: ${{ matrix.SERVICE }}
      run: |
        NORMALIZED_NAME=${{ env.NORMALIZED_NAME }}
        NORMALIZED_NAME=${NORMALIZED_NAME//\//-} # replace / with -
        echo NORMALIZED_NAME=${NORMALIZED_NAME} >> $GITHUB_ENV # update GitHub ENV vars
      shell: bash

    - name: Build and sign image
      uses: golemfoundation/github-actions/octant/docker-build-sign@0.8.3
      with:
        registry: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}
        image-name: ${{ env.NORMALIZED_NAME }}
        image-tag: ${{ inputs.image-tag }}
        context: ${{ matrix.SERVICE }}
        dockerfile: ../ci/Dockerfile.${{ env.NORMALIZED_NAME }}
        wif-provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
        wif-service-account: ${{ vars.GCP_WIF_SA_DEV_WRITER }}
        sign: 'true'

  build-multideployer:
    name: Build Multideployer (special case)
    needs:
      - build-images
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.git-ref }}

    - name: replace placeholders
      run: |
        sed -i 's|_CONTRACTS_IMAGE_PLACEHOLDER_|${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/contracts-v1:${{ inputs.image-tag }}|g' ci/Dockerfile.multideployer
        sed -i 's|_SUBGRAPH_IMAGE_PLACEHOLDER_|${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/subgraph:${{ inputs.image-tag }}|g' ci/Dockerfile.multideployer
      shell: bash

    - name: Build and sign image
      uses: golemfoundation/github-actions/octant/docker-build-sign@0.8.3
      with:
        registry: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}
        image-name: multideployer
        image-tag: ${{ inputs.image-tag }}
        context: localenv/multideployer
        dockerfile: ../../ci/Dockerfile.multideployer
        wif-provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
        wif-service-account: ${{ vars.GCP_WIF_SA_DEV_WRITER }}
        sign: 'true'
