---
name: validate env
on:
  workflow_dispatch:

jobs:
  validate-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: T1
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_BOT_TOKEN }}" https://api.github.com/user)
          if [ "$response" != "200" ]; then
            exit 1
          fi

      - name: T2
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.HOUSEKEEPER_PAT_OCTANT_REPO }}" https://api.github.com/user)
          if [ "$response" != "200" ]; then
            exit 1
          fi
